### PR TITLE
Ale de nic/puzzles v4 aka the rogue branch

### PR DESCRIPTION
**Pull request by TizioMaurizio**
Level developing using experimental meta nonfeatures

### CODE REVIEW

**Comment by TizioMaurizio** [comment]
Desperately looking for experienced git mergers

**Comment by TizioMaurizio** [comment]
Ale next time please after a merge branch from develop

**Comment by TizioMaurizio** [comment]
Thanks to good Stefano's help the conflicts were fixed, lets merge this and then continue the work on puzzles from a correct develop branch

**Review by bottolo — DISMISSED** [review]
It works, and can be useful to us if we want to test a specific area for bugs or something similar. Great!

**Review by bottolo — APPROVED** [review]
Works!

**Pull request merged**
