### PR TITLE
Ale de nic/puzzle v5 the empire strikes back

### LINKED ISSUE #134: Exit from noclip by pressing P only once, now we need to press it twice
After one of the last pushes to develop, we need to press twice to exit no clip (in case we do not move away and return to the body). This is (hopefully) a minor bug.

### PR DESCRIPTION
**Pull request by TizioMaurizio**
new puzzles and other fancy stuff

### CODE REVIEW

**Comment by TizioMaurizio** [comment]
the most awaited commit was finally pushed

**Comment by TizioMaurizio** [comment]
@AleDeNic if we don't expect more features to change or at least nothing huge i would merge this before you continue with the puzzles, do you feel like you need some other tools for level building?

**Comment by TizioMaurizio** [comment]
help needed to merge, i tried locally and couldn't get the timer to work

**Comment by spig95** [comment]
I fixed the bugs with the noclip manager, I would suggest to merge the PR and then work on bugfixing and features adding small changes to the develop.

**Review by spig95 — APPROVED** [review]
I think it works without bugs. The player has a strange cube visible in noclip mode, but we can fix this later 
image

**Comment by TizioMaurizio** [comment]
> I think it works without bugs. The player has a strange cube visible in noclip mode, but we can fix this later image

It's not a bug if you try it you will realize that it is the only way you have to notice the players orientation 😝

**Pull request merged**
