### PR TITLE
add automatic switch camera when the noclip camera is near to the player

### PR DESCRIPTION
**Pull request by stefanofossati**
Implemented feature:
The player in noclip mode automatically pass in reality mode when he is near to the real body

The implementation is done with a simple sphere collider, so the ray of the collider is the variable to set in order to decide the switch distance

### CODE REVIEW

**Comment by TizioMaurizio** [comment]
It's working but noclip camera is always brought back to the same position, shouldn't it start from the player the next time you enable it again?

**Comment by stefanofossati** [comment]
I can put the noclip camera everyware in theory, I have done that because I don't know where the camera has to started

**Comment by TizioMaurizio** [comment]
it's ok, since the behaviour of noclip is not completely formalised yet this is definitely not a mistake, i pointed it out just because it behaves differently on develop and here you can see for an instant the game trying to put the noclip somewhere else before being forced to beginning point

**Comment by TizioMaurizio** [comment]
anyway as soon as conflicts are fixed I will approve

**Review by TizioMaurizio — DISMISSED** [review]

**Comment by stefanofossati** [comment]
I'll do the feature in another branch after the formalization

**Review by spig95 — DISMISSED** [review]
All good from my side!

Btw, I did not notice the `SwitchCamera` function, we can call that function in `NoClipManager` as soon as we activate noclip mode, right? We can do this in another small PR!

**Comment by stefanofossati** [comment]
@spig95  Yes in theory, the method can be call from the outside the class, We have only to make it public in that case

**Review by TizioMaurizio — APPROVED** [review]

**Pull request merged**
