### PR TITLE
Script Template

### PR DESCRIPTION
**Pull request by TizioMaurizio**
add template of unity MonoBehaviour script with several useful features, courtesy of Copilot and RealityMovement.cs

### CODE REVIEW

**Comment by stefanofossati** [comment]
Is this template useful? Do you think that it will be used in future?

**Comment by TizioMaurizio** [comment]
I used it to build the level manager, personally I find it very useful to avoid having to Google singularly all those tools that can come handy

**Review by TizioMaurizio — COMMENTED** [review]
Removed files that had nothing to do with this pull request

**Review by spig95 — APPROVED** [review]
It might be an useful overview, let's keep it!

**Pull request merged**
