### PR TITLE
Feedback menu added... linked to our Google Form!

### LINKED ISSUE #91: Feedback menu
Issue created according to yesterday's meeting to do list

### PR DESCRIPTION
**Pull request by bottolo**
### What's new
- Thanks to the background work built by @stefanofossati, a new feedback menu has been added. 
- UI changes have been made to make it more coherent with the rest. 
- Each answer will be delivered straight to our google form. Hooray!

### Why is this a draft then?
- UI has some really minor bugs. If we can fix them before the 28th, good. If not, it isn't gamebreaking or horrible to watch. Just odd. More specifically, vote buttons don't remain pressed after, well, pressing them. 
- Maybe a back button to iterate through the various responses could be the way to go to enhance user experience.
- Code could use a bit of polishing, but it's not mandatory for this PR. It's just to let _you_ know that it's subject to change.

### CODE REVIEW

**Comment by TizioMaurizio** [comment]
❤️

**Comment by TizioMaurizio** [comment]
This is the link to the form:
https://docs.google.com/forms/d/e/1FAIpQLScXqp9PAHN-KchAizf4vTC3u5GREqvhrbpjt_ar8Sv7aWlXRQ/viewform  
  
Nice menu, I understand it's not easy but it needs to be a bit more fool proof because I managed to fuck it up by histerically pressing all over it to go to next page.
Keep up the great work!

**Review by stefanofossati — APPROVED** [review]
All works as expected, the key L that activates the pause menu is still a problem, but it will be solved by another PR

**Comment by stefanofossati** [comment]
Nothing, I have found a bug: 
- when we started from the menu, the menumanager doesn't have the reference to the objects....so it is not able to send the forms to google

**Review by stefanofossati — CHANGES_REQUESTED** [review]
fix bug on the feedback in pause menu

**Comment by TizioMaurizio** [comment]
is it possible to view the google answers? will the ones we give now for testing mess some kind of average or they are all separate?

**Comment by stefanofossati** [comment]
> is it possible to view the google answers? will the ones we give now for testing mess some kind of average or they are all separate?

I invited you to all the forms yesterday, I think that Google Form allows to see different views, also it allows to create an excel in order to analyze the answers

**Review by stefanofossati — DISMISSED** [review]
It's all ok for me, I'll wait @bottolo approval before merging

**Review by stefanofossati — APPROVED** [review]
Works

**Comment by bottolo** [comment]
> Works

Agreed. GOGO feedbacks!

**Pull request merged**
