### PR TITLE
Impose time limits and respawn when you loose

### LINKED ISSUE #68: Noclip timing or distance constraint
As per title another kind of constraint besides being in a noclip platform needs to be implemented, that is the availability of the game mode once activated.
Is this the last core feature we are missing?

### PR DESCRIPTION
**Pull request by spig95**
### Changes
- Add a component to reality player that makes the player respawn if we hit a time limit to finish a puzzle
- If we set it to 0, there is no time constraint on the puzzle
- The timer "stops" when we activate noclip mode, and it is resumed when in reality mode
- @bottolo added a component in the GUI scene, which shows a timer with the time left to complete the puzzle

### How to use this feature??
The time limit can be changed as a serialize field in the `AnchorCheckpointController`, as shown in the screenshot below. If the time is 0, the puzzle will have no time boundaries.
image

### First timer GUI
image

### CODE REVIEW

**Comment by spig95** [comment]
There is a bug still, the time is reset after switching from noclip to reality, need to work on it!

**Comment by bottolo** [comment]
I'm biased, but this is the best PR ever made.

**Comment by TizioMaurizio** [comment]
ahhhh a dumb proof explanation, exactly as i like them

**Comment by TizioMaurizio** [comment]
I hope the minor change I made is appreciated and didn't break anything, since the timer is quite important I made it quite bigger and moved away the speed meter that was indeed in the middle of the balls

**Comment by TizioMaurizio** [comment]
An important note, it would make sense for the timer to reset everytime we touch a checkpoint platform, otherwise everytime you fall you will have less time to complete the puzzle until you are respawned because out of time

**Comment by bottolo** [comment]
> I hope the minor change I made is appreciated and didn't break anything, since the timer is quite important I made it quite bigger and moved away the speed meter that was indeed in the middle of the balls

Out of the balls updates are the best updates ever made.

> An important note, it would make sense for the timer to reset everytime we touch a checkpoint platform, otherwise everytime you fall you will have less time to complete the puzzle until you are respawned because out of time

Haven't thought about that, I'll check in with Nicola to ensure this is the behaviour to be expected.

**Comment by spig95** [comment]
> > I hope the minor change I made is appreciated and didn't break anything, since the timer is quite important I made it quite bigger and moved away the speed meter that was indeed in the middle of the balls
> 
> Out of the balls updates are the best updates ever made.
> 
> > An important note, it would make sense for the timer to reset everytime we touch a checkpoint platform, otherwise everytime you fall you will have less time to complete the puzzle until you are respawned because out of time
> 
> Haven't thought about that, I'll check in with Nicola to ensure this is the behaviour to be expected.

I can implement that, shall I do it?

**Comment by spig95** [comment]
I have implemented the requested changes by @TizioMaurizio and @AleDeNic, can you please check that is works as expected and, if so, close the PR?

**Comment by TizioMaurizio** [comment]
> I have implemented the requested changes by @TizioMaurizio and @AleDeNic, can you please check that is works as expected and, if so, close the PR?

Good for me, it works also with time equal to 0 by giving you unlimited time, I'll approve and let Ale check it too

**Review by TizioMaurizio — APPROVED** [review]

**Pull request merged**
