### PR TITLE
Area 01 almost done!!!

### PR DESCRIPTION
**Pull request by azazellus**
Almost complete!

Things to do next:
- PUZZLE TIMERS;
- make the post processing work;
- finalize the invisible material;
- write the final dialogues;
- add the tutorial images;
- replace the soundtracks;
- replace the dialogue voices;
- write the loading screens texts;
- replace menu background image;
- CLIFFLATS;
- add icon...

### CODE REVIEW

**Review by stefanofossati — DISMISSED** [review]
Very nice, congratulation to the designer :-)

**Comment by TizioMaurizio** [comment]
what about calling them fliffs

**Review by TizioMaurizio — DISMISSED** [review]
Very nice level design but we can't approve until all exceptions are clear

**Review by stefanofossati — DISMISSED** [review]
👍

**Comment by stefanofossati** [comment]
> Very nice level design but we can't approve until all exceptions are clear

with the merge the exceptions are automatically corrected

**Review by spig95 — DISMISSED** [review]

**Comment by spig95** [comment]
These changes were merged in https://github.com/VDP-noclip/noclip/pull/280

**Pull request closed without merging**
