### PR TITLE
Post Processing SOLVED! Almost.

### LINKED ISSUE #46: Post Processing Effects
This is a reference guide to whoever wants to dive in this issue. I'm currently investigating but I'm afraid I'm not experienced enough to understand how to implement this.

There are multiple ways of handling post processing effects. 

The more convenient method for our purposes is the one involving _LintGammaGain_, which can be accessed like this:
`GameObject` -> `Volume` -> `GlobalVolume` (I would recommend calling it `PostProcessingVolume`). 
Click on the `PostProcessingVolume` and click on "New" on the side, where _Profile_ resides. Then, click on _Add Override_ and add whichever effect you like. To change brightness, I would use _LintGammaGain_, specifically the gamma value.

Whoever comes up with something, I'm all ears.

### PR DESCRIPTION
**Pull request by bottolo**
### Welcome, Post Processing
- This PR introduces Post Processing. It doesn't introduce its variability through sliders, but it manages to implement bloom and vignette. 

### Possible improvements
- Bloom appears too bright when in noclip mode. This can be actually fixed by working on intensity values when enabling noclip mode.

### CODE REVIEW

**Review by stefanofossati — DISMISSED** [review]
Works in reality mode very well

**Review by stefanofossati — APPROVED** [review]
works, there is a strange visual effect but it's all ok

**Comment by azazellus** [comment]
The post processing is great but noclip mode is too bloomy: do we really need those effects for the demo? Do we have the time to fix them?

**Comment by stefanofossati** [comment]
> The post processing is great but noclip mode is too bloomy: do we really need those effects for the demo? Do we have the time to fix them?

@bottolo said that he wants to correct this part this afternoon. So maybe you can ask to him

**Comment by bottolo** [comment]
Even if we don't fix it, simply deleting the PostProcessing game object before building will result in no effects. Therefore, approving and merging doesn't take away anything from the UX side of things

**Pull request merged**
