### PR TITLE
Reality player Movement

### PR DESCRIPTION
**Pull request by stefanofossati**
Main corrections:

- Check the problems of the last controller version
- Find solution and check bugs

### CODE REVIEW

**Comment by stefanofossati** [comment]
The bug of the infinite accelleration on the respawn is still there, I think that the solution could be to reset the player velocity when the player respowns, I'll prepare a method asap

**Comment by TizioMaurizio** [comment]
Habemus controller! hahahaha nice job,I changed max slope to 40 for testing and it works good, I found a nice new feature that has been made possible after polishing: when you are on an edge you can notice you are about to fall, and if you are fast enough you can jump back, also if you are crouching doing so you have more edge for mistake.

**Comment by TizioMaurizio** [comment]
I will approve as soon as the conflicts are resolved, and remember to edit the prefab before merging

**Comment by stefanofossati** [comment]
> I will approve as soon as the conflicts are resolved

I want to wait for the @AleDeNic  approval ahhahha

**Comment by TizioMaurizio** [comment]
> > I will approve as soon as the conflicts are resolved
> 
> I want to wait for the @AleDeNic approval ahhahha

let's goooooooooooooooooo @AleDeNic

**Comment by azazellus** [comment]
The controller works really really well!!
Just a few things:
- when going up on a slope it's perfect, but when you go down the movement is like a continuous series of falls. You can see that in this recording I made: https://drive.google.com/file/d/1sipjVj0QZI9C8D5oYDf59ZftV1h9qwVv/view?usp=share_link
- gravity values should be editable in the inspector, because I would like to change it in order to have a better jump feeling
- "walk speed" should be renamed "run speed" and "sprint speed" shoud be renamed "walk speed"

P.S. I noticed the Tizio's feature (not bug) too and I think it could be very fun!

**Comment by TizioMaurizio** [comment]
>- when going up on a slope it's perfect, but when you go down the movement is like a continuous series of falls. You can see that in this recording I made: https://drive.google.com/file/d/1sipjVj0QZI9C8D5oYDf59ZftV1h9qwVv/view?usp=share_link

I also noticed this but I think it can make sense on very angled slopes to have difficulties moving exactly as you want (but still without weird feelings of sudden accelerations or physics defying events)  
For the slope in your video I believe this goes away by just increasing the gravity, right now it feels like you are on the moon and that's also why it's frustrating

**Comment by azazellus** [comment]
If we use the same angle (e.g. 30°) for every slope in the game, this could help us fixing this issue once and for all

**Comment by stefanofossati** [comment]
> The controller works really really well!! Just a few things:
> 
> * when going up on a slope it's perfect, but when you go down the movement is like a continuous series of falls. You can see that in this recording I made: https://drive.google.com/file/d/1sipjVj0QZI9C8D5oYDf59ZftV1h9qwVv/view?usp=share_link
> * gravity values should be editable in the inspector, because I would like to change it in order to have a better jump feeling
> * "walk speed" should be renamed "run speed" and "sprint speed" shoud be renamed "walk speed"
> 
> P.S. I noticed the Tizio's feature (not bug) too and I think it could be very fun!

@AleDeNic  I'll try to fix the slope tomorrow, after that I'll try also to solve the conflict and if all works fine we can finally merge.
Also I'll do your suggestions

**Comment by stefanofossati** [comment]
Ok I think to have solved the bug, if it's all ok I'll merge @AleDeNic  @TizioMaurizio. In slope scene I have added more object for testing

**Comment by stefanofossati** [comment]
I have found a possible problem: With the no-friction material when the player collide with a wall it continue to move right or left if the player isn't perpendicular to the wall. Maybe we can add a check that change the material in order to avoid this problem

**Comment by azazellus** [comment]
Mmmh the problem of going down the slope is still there. And I noticed that now when you are steady on a slope you slide down.

**Comment by stefanofossati** [comment]
ok now the controller should works well

**Comment by AleDeNic** [comment]
Nice, now everything works fine! The next step after this PR is in the new issue I opened.

**Review by azazellus — APPROVED** [review]
Nice, now everything works fine! The next step is in the new issue I opened, "Player Movement: ultimate polishing."

**Pull request merged**
