### PR TITLE
Change reality player size

### LINKED ISSUE #117: Player is too small
As reported by some testers when playing it feels like you are too small, we should either make the player bigger or the world smaller

### PR DESCRIPTION
**Pull request by stefanofossati**
I have tried to do bigger the reality player:
- I have modified the size of the player;
- I have adapted the groundcheck that is hardcoded

### CODE REVIEW

**Comment by stefanofossati** [comment]
@TizioMaurizio @AleDeNic check if it is better than before

**Comment by azazellus** [comment]
YES! It's soooo much better!

**Comment by TizioMaurizio** [comment]
> YES! It's soooo much better!

is it tall enough?
anyway I made the player capsule round, nothing changed just the appearance

**Comment by azazellus** [comment]
> is it tall enough? anyway I made the player capsule round, nothing changed just the appearance

I think it's good, don't you agree?

**Comment by TizioMaurizio** [comment]
> > is it tall enough? anyway I made the player capsule round, nothing changed just the appearance
> 
> I think it's good, don't you agree?

I couldn't notice the difference but maybe it's just because of the textures, let's keep it this way and see if someone complains during testing

**Review by TizioMaurizio — APPROVED** [review]

**Pull request merged**
