### PR TITLE
Pause Settings mini PR

### LINKED ISSUE #83: Pause Menu Settings
As of right now, sliders and such don't work in the new pause menu. This needs to be addressed, and I'll look into it as soon as possible.

### PR DESCRIPTION
**Pull request by bottolo**
This PR adjusts the pause menu. 
- Fixed bug where sliders didn't work properly
- Added mixer and refactored code to accomodate it
- Added a skeleton of the settings
- Mixer working with pause menu settings
- Exit now leads you to the main menu

Known issues:
- If you invert Y, it does so. But you won't be able to invert it again
- Sensitivity check not working

For now, take this PR as an update on the pause menu visuals and options.
If you have suggestions on why checks aren't working, you can suggest them here and I'll bring those changes in this PR!

### CODE REVIEW

**Comment by bottolo** [comment]
- Removed crosshair outline

**Comment by bottolo** [comment]
- I've finished, I swear

**Comment by stefanofossati** [comment]
The sliders of audio and gameplay save the value but they seem to not modifing the setting effectively

**Comment by bottolo** [comment]
> The sliders of audio and gameplay save the value but they seem to not modifing the setting effectively

Gameplay settings now work as intended, audio has to be fixed in another PR.

**Review by stefanofossati — APPROVED** [review]
Ok the sensitivity is fixed from 0_Main

**Pull request merged**
