### PR TITLE
Score is shown in game if the user presses "Info"

### PR DESCRIPTION
**Pull request by spig95**
If you like this feature, we can add also a Joystick button for this and, in addition, put the instructions in the control image.

### CODE REVIEW

**Review by stefanofossati — DISMISSED** [review]
Works, but I think that if is ok for @AleDeNic we have to decide the specific key for both keyboard and joystick

**Comment by azazellus** [comment]
Hey! We could use P in the keyboard and the select key in the gamepad.

**Comment by azazellus** [comment]
image

**Comment by azazellus** [comment]
There are too many keys, it could be confusing, but nobody will read the controls so there's no problem hahaha

**Review by bottolo — APPROVED** [review]
F*ck the infos

**Pull request merged**
